package hr.java.game.dixitmultiplayergame.model;

public enum MessageType {
    MAX_PLAYERS_REACHED,
    GAME_ALREADY_IN_PROGRESS,
    ASSIGN_PLAYER,
    UPDATE_PLAYER_LIST,
    UPDATE_STORYTELLER,
    UPDATE_PLAYER_CARDS,
    UPDATE_PLAYER_WITH_TURN,
    UPDATE_LOADED_PLAYER_WITH_TURN,
    UPDATE_STORYTELLER_DESCRIPTION,
    UPDATE_POINTS,
    STORYTELLER_CARD_AND_DESCRIPTION_SELECTED,
    PLAYER_CARD_SELECTED,
    CHOSEN_CARD_SELECTED,
    SERVER_SEND_SUBMITTED_CARDS_FOR_VOTING,
    REVEAL_STORYTELLER_CARD,
    DRAW_CARDS,
    CONTINUE_NEXT_ROUND,
    GAME_OVER,
    SEND_SAVE_REQUEST_TO_SERVER,
    SERVER_SENDING_LOADED_DATA,
    UPDATE_PLAYER_CARDS_LOADED
}
